### ISSUE TITLE
[FEAT] 바텀 네비게이션 구현

### ISSUE THREAD

**Issue by jinsilWoo** [jinsilWoo/Jinsil-s-LAB#1]
## 🤍 Issue

ViewPager2 를 활용한 BottomNavigation 구현하기

## 📌 To-do

- [x] BaseFragment, BaseActivity  적용해보기
- [x] fragment 간 ViewPager2 적용
- [x] BottomNavigation 구현
- [x] BottomNavigation 과 ViewPager 연결
